kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-elastic-proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pto-elastic-proxy.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
  env:
    - name: VEILARBPORTEFOLJE_ELASTICSEARCH_URL
      value: https://elastic-pto-veilarbportefolje-es-nav-dev.aivencloud.com:26482
  elastic:
    instance: veilarbportefolje-es
    access: readwrite


